{
 "title": "DevOps API Dashboard",
 "refresh": "10s",
 "panels": [
  {
   "title": "Requêtes HTTP par seconde",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(http_requests_total[1m])",
     "legendFormat": "{{method}} {{route}} {{status_code}}"
    }
   ]
  },
  {
   "title": "Total Requêtes",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "sum(http_requests_total)", "legendFormat": "Total" }
   ]
  },
  {
   "title": "CPU Usage (%)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)"
    }
   ]
  },
  {
   "title": "RAM utilisée (%)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100"
    }
   ]
  }
 ]
}